export const POST_TRAVELLER_DETAILS = "POST_TRAVELLER_DETAILS";
export const FETCH_TRAVELLERS = "FETCH_TRAVELLERS";
export const SINGLE_TRAVELLER = "SINGLE_TRAVELLER";
// trains
export const FETCH_TRAINS = "FETCH_TRAINS";
export const FETCH_TRAINS_DESTINATION = "FETCH_TRAINS_DESTINATION";
export const SINGLE_TRAIN = "SINGLE_TRAIN";
