export const SEARCH_TRAIN = "SEARCH_TRAIN";
export const FETCH_TRAINS = "FETCH_TRAINS";
export const CREATE_TRAVELLER_DESTINATION = "CREATE_TRAVELLER_DESTINATION";
export const FETCH_TRAVELLERS= "FETCH_TRAVELLERS";
